import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import React from "react";
import { Toaster } from "../components/ui/toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // ClerkProvider is a wrapper that provides Clerk's authentication and session management
    <ClerkProvider>
      <html lang="en">
        <body className="">
          {children}
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
